---
name: docker-build-and-publish

on:
  workflow_dispatch:
    inputs:
      tag_name:
        type: string
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: true

  workflow_call:
    inputs:
      tag_name:
        type: string
        description: 'Tag name for the release (e.g., v1.0.0)'
        required: true

env:
  repository: ${{ github.repository || 'thevickypedia/pyfilebrowser' }}
  repository_name: ${{ github.repository.name || 'pyfilebrowser' }}
  repository_description: ${{ github.event.repository.description || '📂 Web File Browser' }}
  # workflow_call first, fallback to workflow_dispatch
  tag_name: ${{ inputs.tag_name || github.event.inputs.tag_name }}

jobs:
  release:
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Login to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          push: true
          platforms: linux/amd64,linux/arm64
          tags: ${{ env.repository }}:${{ env.tag_name }},${{ env.repository }}:latest
          build-args: |
            VERSION=${{ env.tag_name }}
          secrets: |
            git_token=${{ secrets.GIT_TOKEN }}
            repo_name=${{ env.repository }}

      - name: Update description
        uses: thevickypedia/describe-docker@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          summary: "${{ env.repository_description }}"
          repository: "${{ env.repository_name }}"
          filename: "README.md"
