name: none-shall-pass

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - "**/*.md"

jobs:
  none-shall-pass:
    runs-on: thevickypedia-default
    steps:
      - uses: thevickypedia/none-shall-pass@v5
