name: pypi-publish

on:
  release:
    types: [ published ]
  workflow_dispatch:

jobs:
  pypi-publisher:
    outputs:
      version: ${{ steps.pypi_publisher.outputs.version }}
    runs-on: thevickypedia-default
    steps:
      - id: pypi_publisher
        uses: thevickypedia/pypi-publisher@v5
        env:
          token: ${{ secrets.PYPI_TOKEN }}
  docker-build-and-publish:
    needs:
      - pypi-publisher
    uses:
      ./.github/workflows/build-publish.yml
    with:
      tag_name: ${{ needs.pypi-publisher.outputs.version }}
      # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#release
      # https://docs.github.com/en/webhooks/webhook-events-and-payloads?actionType=released#release
      latest: ${{ github.event_name == 'release' && !github.event.release.prereleased }}
    secrets: inherit
